### ISSUE TITLE
[3] Rajouter une case à cocher sur l'écran du mot de passe [S]

### ISSUE THREAD

**Issue by maxbook** [abibao/dashboard#13]
Cf screenshot "onboarding-ecran2...". Elle doit être cochée pour passer à l'étape suivante. Liens vers CGU : http://abibao.com/cgu.html et vers vie privée : http://abibao.com/prvp.html

**Comment by boitaumail** [comment]
Obsolète. CF https://github.com/abibao/dashboard/issues/39
