### ISSUE TITLE
Ajouter un loading state sur les bouton

### ISSUE THREAD

**Issue by maxbook** [abibao/dashboard#22]
Ajouter un loading state sur les bouton lors des appels à l'API

**Comment by maxbook** [comment]
Bon sur le boutons je viens de commencer à le faire mais... on a pas forcement de bouton valider sur toutes les questions :/

**Comment by boitaumail** [comment]
Suite à notre échange. Part sur un loader qui apparaît par dessus le bloc question en fondu.

**Comment by boitaumail** [comment]
Slt Max, as-tu prévu de placer en "disabled" sur le bouton du "register".
A priori on a eu des requêtes multiples (avec une fraction de secondes d'écart) et ca fait buguer l'onboarding.

**Comment by maxbook** [comment]
Hello, j'ai fais un test avec une loading bar, qui est généraliste donc fonctionne à chaque appel HTTP, fais moi un retour :)

**Comment by maxbook** [comment]
Le bouton register passe maintenant en disabled quand le form est soumis

**Comment by boitaumail** [comment]
Très bien. Ca fonctionne en reset. C'est discret et visible. J'aime beaucoup !
Je clos. Bien joué.
