### ISSUE TITLE
[2] integrer cas onboarding quand on vient d'une asso

### ISSUE THREAD

**Issue by maxbook** [abibao/dashboard#23]

**Comment by boitaumail** [comment]
Faire le point avec Gilles pour la technique.
Il est question d'avoir 1 page statique HTML par association (Créées et gérées par Vincent) qui renvoient vers le dashboard avec 2 paramètres en GET (1:l'email et 2:l'identifiant de l'asso).
Voir avec Gilles pour l'identifiant de l'asso.
