### ISSUE TITLE
Mauvais champ utilisé dans la selection Asso

### ISSUE THREAD

**Issue by boitaumail** [abibao/dashboard#25]
Cf cette écran qui résume la situation :
https://drive.google.com/file/d/0B869k4RQhtxFRTRfYkdiMkpPakE/view?usp=sharing

Là où tu devrais utiliser le champ "name" (dans la liste de gauche), tu utilises le champ "title".
Ces 2 champs sont différents car dans la pratique "name" peut-être plus court que "title".

**Comment by maxbook** [comment]
Corrigé dans le commit fc002d99e052fbffad10239ce6f0ee2d51bf83e5
