### ISSUE TITLE
[5] Pb si submit de réponse après un "previous"

### ISSUE THREAD

**Issue by boitaumail** [abibao/dashboard#27]
Le problème se trouve au niveau de la fonctionnalité next/previous via les icones flèches au cours d'un sondage.

Si je fais "previous" et que je répond à une question, alors apparaot le moyen de faire un next de plus. Ce qui pourrait me faire louper une question laissée dans réponses.

Si lourd à gérer, on peut envisager permettre le previous mais pas le next.

**Comment by maxbook** [comment]
Bien vu ! ^^ dans ce cas je vais remplacer ce système par un autre, quand on aura la partie qui permet d'enregistrer les réponses dans angular. Je verrais ça en même temps que l'issue #3
