### ISSUE TITLE
[3] Intégrer l'état des choix SELECTED [L]

### ISSUE THREAD

**Issue by maxbook** [abibao/dashboard#3]
[Cf IMAGE] Faire le CSS du cas "selected", j'ai mis en image le screen de Gildas

**Comment by boitaumail** [comment]
Tu peux même consulter ce dossier qui contiens les éléments (dont le screen) :
https://drive.google.com/drive/folders/0B6V-cx-TEoMFUDJSSVlSTHVrOXc

**Comment by maxbook** [comment]
#5
