### ISSUE TITLE
Permettre le HTML dans titre et description

### ISSUE THREAD

**Issue by boitaumail** [abibao/dashboard#39]
Pour le cas des CGU nous avons besoin de mettre un lien href.
Il nous faut pouvoir mettre du html dans la description des questions. A généraliser aussi dans le champ titre.

**Comment by maxbook** [comment]
Cette solution est-elle toujours d'actualité ?

**Comment by boitaumail** [comment]
Oui,
Comme nous en avions discuté par téléphone ensemble. Nous allons utiliser une des questions du sondage 01 pour faire accepter les CGU.
Il nous faut pouvoir ajouter un lien pour consulter les CGU (et politique de confidentialité). Donc dans l'immédiat il nous faut pouvoir afficher du <a href= dans la description ET/OU le titre.

**Comment by maxbook** [comment]
Je vois ça pour la description

**Comment by abibao** [comment]
done
